### ISSUE TITLE
Circular references..

### ISSUE THREAD

**Issue by waynebrantley** [brockallen/CookieTempData#1]
It seems that there are circular references in the object hierarchy which is not supported by the JSON serializer.  

In my case it was:
A circular reference was detected while serializing an object of type 'System.Globalization.CultureInfo'.

I am simply trying to serialize the ModelState from MVC (most common thing needed)

Seems most people use binary formatter...
var memStream = new MemoryStream();
            memStream.Seek(0, SeekOrigin.Begin);
            var binFormatter = new BinaryFormatter();
            binFormatter.Serialize(memStream, values);
            memStream.Seek(0, SeekOrigin.Begin);
            var bytes = memStream.ToArray();
            return Convert.ToBase64String(bytes);

http://afana.me/post/session-less-controllers-and-TempData-ASPNET-MVC.aspx
http://aspnetwebstack.codeplex.com/SourceControl/changeset/view/1d34d93f0665#src%2fMicrosoft.Web.Mvc%2fCookieTempDataProvider.cs

**Comment by brockallen** [comment]
Hey Wayne -- I've got no problem switching over to the binary formatter. I'll close this out once I update.

**Comment by brockallen** [comment]
Ok, updated to use BinaryFormatter and NuGet is updated as well.
