### ISSUE TITLE
Public CookieTempDataControllerFactory 

### ISSUE THREAD

**Issue by KiarashS** [brockallen/CookieTempData#10]
Hi,

Please change  Access Modifiers in `CookieTempDataControllerFactory` to public.

**Comment by brockallen** [comment]
Why do you need it public?

**Comment by KiarashS** [comment]
I want call `CookieTempDataControllerFactory` in my IOC container, but now i can't call that, so i can't use NuGet package of CookieTempData and i use CookieTempData source code directly in my project.

**Comment by brockallen** [comment]
Ok, so you have a solution then. I'll close the issue. Thx,

**Comment by KiarashS** [comment]
Why did not you make it public?

**Comment by brockallen** [comment]
I thought you made a copy in your own project and thus were happy. I misunderstood.

**Comment by KiarashS** [comment]
If you make that public, so developers can call `CookieTempDataControllerFactory` in their projects(for any reason) and easily update usefull `CookieTempData` library from the NuGet(otherwise they need to make a local copy and remain unaware from `CookieTempData` updates/releases).

**Comment by brockallen** [comment]
Ok, done. v1.3 on nuget.

**Comment by KiarashS** [comment]
very thanks :)
