### ISSUE TITLE
Move dependencies to NuGet packages

### ISSUE THREAD

**Issue by jkodroff** [brockallen/CookieTempData#14]
I'm experiencing an error on my build server when building the views on my MVC project:

`
(MvcBuildViews target) -> 
[14:23:30][Step 1/1]   error ASPRUNTIME : The pre-application start initialization method Start on type BrockAllen.CookieTempData.AppStart threw an exception with the following error message: Could not load file or assembly 'Microsoft.Web.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. [C:\TeamCity\buildAgent\work\5e9fa80329d6276\src\RelocationMoverServices.Web.UI\RelocationMoverServices.Web.UI.csproj]
[14:23:30][Step 1/1] 
`

I noticed there are a couple of dependencies here that could be moved to NuGet packages:
1. Microsoft.Web.Infrastructure
2. System.Web.Mvc
3. Possibly other stuff, which I might find if I dug deeper.

What's the minimum version of MVC that you need to support?  Let me know and I'd be down to attempt a PR.

**Comment by brockallen** [comment]
Yea, this might be an error due to some of Msft's recent MVC changes. I'd have to look, but don't have a lot of time. If you can diagnose, it'd be helpful

**Comment by luisgoncalves** [comment]
The project is on MVC 3 and I've tested it with MVC 5.2.X.

Maybe something like `<dependency id="Microsoft ASP.NET MVC" version="[3,6)" />` for a start.

**Comment by luisgoncalves** [comment]
@jkodroff: any chance you can take a look into this? I'd like to resolve #11 but it'd be nice to have the dependencies as Nuget packages already.

**Comment by jkodroff** [comment]
I believe (but am by no means certain) that MVC 3 could no longer be supported because MVC 3 is not delivered as a NuGet package - it's installed to the system.

Again, not sure, but I believe we could do `[4,6)`, and I'd certainly be willing to try it.

The question is whether @brockallen is willing to cease support for MVC 3 if necessary, per my question above.

**Comment by brockallen** [comment]
Well, since we have a working solution for MVC3, if people want it they can get the old code/ NuGet. So yea, I'm fine w/ moving to MVC4 or 5.

**Comment by brockallen** [comment]
Any PR forthcoming?

**Comment by jkodroff** [comment]
Yes.  This week.  I promise.  Sorry for the delay.

**Comment by brockallen** [comment]
I'd not knock yourself out -- ASP.NET 5 is right around the corner so this might be a bit late to bother with.
