### ISSUE TITLE
Cookie limits problematic for validation

### ISSUE THREAD

**Issue by jtheisen** [brockallen/CookieTempData#15]
Even modern browsers appear to have a mean size limit. Chrome and Firefox let you have 4K sharp, IE11 not much more.

Even though CookieTempData compresses the key-value-pairs, this can quickly get to be too little.

If the data get's above 4K, what happens is that the browser (Chrome anyway) will not store the cookie and the temp data is simply lost.

Arguably, an exception would be better here, especially during debugging. Conceivable is also to have the information truncated somehow and pass the problem through the temp data so that the page can display a nicer error message to the user.

**Comment by brockallen** [comment]
Not sure. If you have a solution, then make a proposal and you can do a PR.

**Comment by jtheisen** [comment]
It was the cookie size limit - not something more subtle as I thought before. I updated the description.

**Comment by brockallen** [comment]
Yea, well, I don't have much to offer then -- don't put so much data in there.

**Comment by jtheisen** [comment]
In an example form I have with 10 fields, 4 validation errors and _no_ actual input, I already get the Cookie to burst.

That means that in its current state, CookieTempData isn't really suited for using it for validation. Even with smaller forms the user input could easily still burst the cookie, and there is no error handling for those cases.

Also, according to some superficial research I did, the serialization appears to be wasteful.

For the case during development where my cookie burst, I made the following measurements (TempDataContent further below):
- Json.NET unindented serialized length: 1522 (same as below without the indentation)
- Json.NET unindented compressed length: 375

That's not too much, but the following is what CookieTempData gets from the tools it uses:
- serializedWithBinaryFormatter size: 9630
- compressed size: 3044
- compressed and protected: 4141

And that's already blowing it.

Either `SerializeWithBinaryFormatter` is really wasteful or it serializes something that Json.NET skips. I haven't tested that.

Here's the actual content, just for plausibility (it's what Json.NET gets from the dictionary):

```
  "__MvcContrib_ValidationFailures__": {
    "id": {
      "Value": {
        "AttemptedValue": "2d474f3b-1a61-4c21-af92-f79c0a3edbd9",
        "Culture": "(Default)",
        "RawValue": [
          "2d474f3b-1a61-4c21-af92-f79c0a3edbd9"
        ]
      },
      "Errors": []
    },
    "PaymentMethod": {
      "Value": {
        "AttemptedValue": "InvoicePrePaid",
        "Culture": "de-DE",
        "RawValue": [
          "InvoicePrePaid"
        ]
      },
      "Errors": []
    },
    "CustomerName": {
      "Value": {
        "AttemptedValue": "",
        "Culture": "de-DE",
        "RawValue": [
          ""
        ]
      },
      "Errors": [
        {
          "Exception": null,
          "ErrorMessage": "The Customer name field is required."
        }
      ]
    },
    "ContactPersonName": {
      "Value": {
        "AttemptedValue": "",
        "Culture": "de-DE",
        "RawValue": [
          ""
        ]
      },
      "Errors": []
    },
    "PhoneNumber": {
      "Value": {
        "AttemptedValue": "",
        "Culture": "de-DE",
        "RawValue": [
          ""
        ]
      },
      "Errors": [
        {
          "Exception": null,
          "ErrorMessage": "The Phone number field is required."
        }
      ]
    },
    "EmailAddress": {
      "Value": {
        "AttemptedValue": "some.user@example.com",
        "Culture": "de-DE",
        "RawValue": [
          "some.user@example.com"
        ]
      },
      "Errors": []
    },
    "AddressLine1": {
      "Value": {
        "AttemptedValue": "",
        "Culture": "de-DE",
        "RawValue": [
          ""
        ]
      },
      "Errors": [
        {
          "Exception": null,
          "ErrorMessage": "The Address line 1 field is required."
        }
      ]
    },
    "AddressLine2": {
      "Value": {
        "AttemptedValue": "",
        "Culture": "de-DE",
        "RawValue": [
          ""
        ]
      },
      "Errors": [
        {
          "Exception": null,
          "ErrorMessage": "The Address line 2 field is required."
        }
      ]
    },
    "AddressLine3": {
      "Value": {
        "AttemptedValue": "",
        "Culture": "de-DE",
        "RawValue": [
          ""
        ]
      },
      "Errors": []
    },
    "Country": {
      "Value": {
        "AttemptedValue": "Deutschland",
        "Culture": "de-DE",
        "RawValue": [
          "Deutschland"
        ]
      },
      "Errors": []
    },
    "TaxNumber": {
      "Value": {
        "AttemptedValue": "",
        "Culture": "de-DE",
        "RawValue": [
          ""
        ]
      },
      "Errors": []
    }
  }
```

**Comment by jtheisen** [comment]
I incorrectly assumed that using TempData to carry model state data is typical, which isn't the case.

Closing.
