### ISSUE TITLE
Problem With CookieTempData

### ISSUE THREAD

**Issue by KiarashS** [brockallen/CookieTempData#3]
Hello,
CookieTempData not worked in my app(MVC 4 & DOT.NET 4.5),so i changed CookieTempDataControllerFactory class to public and removed 'PreApplicationStartMethod' attribute and call 'AppStart.Start' in my 'Global.asax.cs',Now that work!!!

what is couse of this problem?

**Comment by brockallen** [comment]
I can't say without more information. What do you mean by "CookieTempData not worked in my app"?

**Comment by KiarashS** [comment]
Also i can't say more information !!! because that not display any exception message and not logged anything by my Elmah logger!
Only when i redirect to another page that redirect me to Error page!!!!

**Comment by brockallen** [comment]
You need to debug and provide me more information for me to help you.

**Comment by KiarashS** [comment]
I found couse of this problem,
I use StructureMap for Dependency Injection and in global.asax.cs i override GetControllerInstance of DefaultControllerFactory class,which StructureMap inject dependencies to controller via this controller factory.

CookieTempData use "PreApplicationStartMethod" for register provider,which in this case because i overrided controller factory,CookieTempData not work.

@brockallen  i solved this problem with changing "PreApplicationStartMethod" to "PostApplicationStartMethod" and now CookieTempData work nice.

I suggest to you change "PreApplicationStartMethod" to "PostApplicationStartMethod",which in this case users can register their controller factories without any problem.

in "PreApplicationStartMethod" mode users can't register their controller factories.

**Comment by brockallen** [comment]
Yes, I knew there were issues/conflicts with IoC containers. I'll put this on my TODO list.

**Comment by brockallen** [comment]
I updated it to simulate the PostAppStart from the webactivator library -- I didn't want to add the dependency.
https://github.com/brockallen/CookieTempData/commit/903c6c88f5efa8838370331ae8e768aef72de252
