### ISSUE TITLE
TempData on SignOut

### ISSUE THREAD

**Issue by sweeperq** [brockallen/CookieTempData#6]
I just started using CookieTempData provider on a site I'm developing. I'm utilizing it to store success/error messages that need to be preserved on redirects.

It works well on most pages. However, if I use it when signing out of my site using FormsAuthentication.SignOut(), the TempData is not persisted on the Redirect.

I used Fiddler to verify that there are no intermediate redirects occurring.

I wasn't sure if FormsAuthentication.SignOut() was doing something extra behind the scenes so I tried manually expiring the authentication cookie. However, the odd behavior still occurred.

I'm wondering if it has something to do with expiring HttpOnly auth cookies.

This was in VS 2013 / Embedded IIS / .Net 4.5

**Comment by brockallen** [comment]
TempData is signed and part of the input to the signature is the current username. So if you're preserving tempdata across a request where the authentication is changed (signin or signout) then the tempdata will be corrupt (will not work).

**Comment by sweeperq** [comment]
Thank you for verifying. I wanted to make sure it was isolated to authentication and didn't have something to do with getting/setting other cookies.

**Comment by brockallen** [comment]
No problem.
