### ISSUE TITLE
Error occurred during a cryptographic operation

### ISSUE THREAD

**Issue by ChewYoungPen** [brockallen/CookieTempData#9]
System.Security.Cryptography.CryptographicException
 Error occurred during a cryptographic operation.

Summary of scenario

IdPSrv v2 -> ADFS -> SharePoint.

IdPSrv exists on two servers with load traffic manager serving requests.
 ADFS farm with primary, secondary and two proxies.
 SharePoint has a single WFE.

When I log in I'm passed around and eventually hit SharePoint. I wait without clicking on anything for 50 minutes (49 minutes is fine) and then click to move to another page. I get passed back to IdPServ (via ADFS) and the cryptographic operation leaps out.

Suspect that its because the IdPServ exists on two servers - and the machine key's aren't set on them.

**Comment by ChewYoungPen** [comment]
Related to https://github.com/brockallen/CookieTempData/issues/5#issuecomment-45202651

**Comment by ChewYoungPen** [comment]
Always the way. Search and search and not find anything, then post and find

http://brockallen.com/2013/02/18/configuring-machine-key-protection-of-session-tokens-in-wif-and-thinktecture-identitymodel/

Doh!

I'll try this and see if it fixes the problem.

**Comment by ChewYoungPen** [comment]
All good!

I added a machine.config entry to add the same machine key across the server farm and the error has vamooshed!

Closing issue.

Thanks.

**Comment by brockallen** [comment]
Sorry, was traveling. Good to hear it's back to working.
